### ISSUE TITLE
Additional include path for Python

### ISSUE THREAD

**Issue by waarmond** [adobe/USD-Fileformat-plugins#10]
Thanks for the helping me with https://github.com/adobe/USD-Fileformat-plugins/issues/5

At setup of USD-ff-plugins with `cmake --build build --config release` the Boost.Python module expects python include files at /usr/include/ and isn't looking at `/usr/include/python3.10/`
```
/usr/include/boost/python/detail/wrap_python.hpp:178:11: fatal error: Python.h: No such file or directory
  178 | # include <Python.h>
```
I've tried 
```
  export CFLAGS+=" -I/usr/include/python3.10"
  export CPPFLAGS+=" -I/usr/include/python3.10"
```
but it is not respected – symlinking however works well. How may I pass an additional searchpath?

--

After passing this roadblock I'm stumbling at

```
[ 16%] Linking CXX shared library libfileformatUtils.so
mold: fatal: library not found: tf
```

**Comment by kwblackstone** [comment]
Glad #5 was resolved!

Hmm, both of these point to some sort of environment issue.  For the python issue you can try passing in:
-DPYTHON_INCLUDE_DIR=/usr/include/python3.10 to your cmake configure command and see if that helps.  You may also need -DBoost_INCLUDE_DIR=/usr/include/

but I would try just the PYTHON_INCLUDE_DIR first.

Not finding tf sounds like the LD_LIBRARY_PATH hasn't been updated.  I'll refer back to the readme [here](https://github.com/adobe/USD-Fileformat-plugins?tab=readme-ov-file#1-setup-dependencies)

Specifically, appending your <USD_INSTALL_PATH>/lib to the LD_LIBRARY_PATH.

Let me know if this helps!

**Comment by kwblackstone** [comment]
Closing this with the above suggestions, let us know if you are still having issues.
