### ISSUE TITLE
Unable to build FBX plugin

### ISSUE THREAD

**Issue by TheMostDiligent** [adobe/USD-Fileformat-plugins#12]
Hello!

I am trying to follow the steps to build the FBX plugin: I downloaded and installed the FBX sdk and provided a path to it through the `FBXSDK_ROOT` CMake variable. However, CMake configuration steps fails with the following error:

```
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
-- PROJECT VERSION IS: 1.0.2
Building without ASM
-- Fetching GTest
-- Fetching libxml2
CMake Error at C:/Program Files/CMake/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find FBXSDK (missing: FBXSDK_LIBRARIES)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindFBXSDK.cmake:101 (find_package_handle_standard_args)
  fbx/CMakeLists.txt:10 (find_package)
```

There are no CMake files in the SDK folder, and the [FindFBXSDK.cmake](https://github.com/adobe/USD-Fileformat-plugins/blob/main/cmake/FindFBXSDK.cmake) does not set the `FBXSDK_LIBRARIES` variable.

The plugins build fine without FBX (`-DUSD_FILEFORMATS_ENABLE_FBX=OFF`)
Can you please suggest how the build should be set up to enable FBX?

**Comment by kwblackstone** [comment]
Hello,

My initial thought is that this might be related to the CMake version you're using. Could you please confirm which version of CMake you have installed? If it's older than 3.24 please update to atleast that version.

If updating CMake doesn't resolve the issue, please double-check that the FBX SDK is correctly installed at the location specified in the -DFBXSDK_ROOT variable. Ensure that this path directly points to the directory containing the SDK's lib and include folders.

Lastly, could you share the exact CMake command you are using to configure the project? This may help figure it out.

Thanks!

**Comment by TheMostDiligent** [comment]
@kwblackstone Thank you for looking into this issue!

>  Could you please confirm which version of CMake you have installed?

3.24.1

> Ensure that this path directly points to the directory containing the SDK's lib and include folders.

I set the path to point to the SDK root folder. This is what is in the folder:

![image](https://github.com/adobe/USD-Fileformat-plugins/assets/61806567/ef0d9817-d1bd-4322-905e-8c667069b1ac)

> Lastly, could you share the exact CMake command you are using to configure the project? This may help figure it out.

```
cmake -S . -B build/Debug -DCMAKE_INSTALL_PREFIX=bin -Dpxr_ROOT=c:\GitHub\OpenUSD\build\Debug -DFBXSDK_ROOT=c:\GitHub\FBX_SDK_2020.3.7
```

**Comment by TheMostDiligent** [comment]
@kwblackstone I renamed `vs2019` to `vs2022` in the FBX SDK and it worked - thank you!
Note that starting with VS2015, static libraries [built with one version are compatible with another version](https://learn.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=msvc-170). So that for VS2022 it is totally OK to use static libs built for VS2019 - exact match is not required.
