### ISSUE TITLE
FBX and USDSBSAR optional

### ISSUE THREAD

**Issue by fire** [adobe/USD-Fileformat-plugins#18]
### Expected Behaviour

https://github.com/adobe/USD-Fileformat-plugins?tab=readme-ov-file#dependencies

FBX and USDSBSAR should be optional for a FOSS build.

### Actual Behaviour

The documentation says they're required.

### Reproduce Scenario (including but not limited to)

See https://github.com/adobe/USD-Fileformat-plugins readme.

#### Steps to Reproduce

See https://github.com/adobe/USD-Fileformat-plugins readme.

#### Platform and Version

https://github.com/adobe/USD-Fileformat-plugins/commit/1b58b829fae192c206f2b4e6bbb834b5ecf89a30 MacOS M2 Pro

**Comment by kwblackstone** [comment]
Hello, maybe the documentation isn't clear enough, but both FBX and Substance are optional and can be turned off via -DUSD_FILEFORMATS_ENABLE_FBX and -DUSD_FILEFORMATS_ENABLE_SBSAR (the second of which isn't on the README and I shall add it.

The graph is showing:
FBX SDK  2020.2.1	usdfbx	no
meaning the FBX SDK is not optional for the usdfbx plugin.  

Similarly for Substance:
Substance  9.1.2	usdsbsar	no
meaning the Substance SDK is not optional for the usdsbsar plugin.

Hope this helps!
