### ISSUE TITLE
Supported features legend 

### ISSUE THREAD

**Issue by fire** [adobe/USD-Fileformat-plugins#2]
### Expected Behaviour

Supported features legend marks support of the 3d asset formats.

### Actual Behaviour

There is no use of supported features legend.

### Reproduce Scenario (including but not limited to)

Visit the website.

#### Steps to Reproduce

Read https://github.com/adobe/USD-Fileformat-plugins readme

#### Platform and Version

Mac OS

#### Sample Code that illustrates the problem

This is markdown documentation

#### Logs taken while reproducing problem

None

**Comment by fire** [comment]
That makes sense. Perhaps you can add:

> Each format's readme contains what they support.

**Comment by kwblackstone** [comment]
added a comment to the global readme pointing users to each file formats readme.
