### ISSUE TITLE
Compatibility with Apple AR Quicklook

### ISSUE THREAD

**Issue by thearperson** [adobe/USD-Fileformat-plugins#27]
We are debugging some texture issues related to USD files created using Adobe USD Fileformat Plugin

![IMG_0001](https://github.com/adobe/USD-Fileformat-plugins/assets/78055277/7daf85ad-6818-464d-8474-4ed8bf39133e)

It seems that Apple is complaining about `NodeGraph` 

```
$ ./USD/usdchecker --arkit /Users/jwcai/Downloads/quicklook.usdz
Stage does not specify an upAxis. (fails 'StageMetadataChecker')
Prim </a790c383_2ae6_4800_8652_b14081af6518_mesh/Materials/defaultMat_/UsdPreviewSurface> has unsupported type 'NodeGraph'. (fails 'ARKitPrimTypeChecker')
Failed!
```

Which is in turn originated here:

https://github.com/adobe/USD-Fileformat-plugins/blob/aee03b4129d542371e708de5f0779e2d3fd6d7f2/utils/layerWriteMaterial.cpp#L207C82-L207C91

the usdchecker is from https://developer.apple.com/augmented-reality/tools/files/USDPython-pkg.zip

Wondering whether it's more suitable to create a simpler UsdPreviewSurface without involving `NodeGraph`?

**Comment by thearperson** [comment]
update:

I also asked about this at the Apple Forum: https://developer.apple.com/forums/thread/756638

Turns out `NodeGraph` is not the immediate issue, using `inputs:file.connect` is the real one that can't be handled properly.

**Comment by kwblackstone** [comment]
Thanks @thearperson for the report and the follow up.  We are aware that not all of our output works properly with ArKit. An ArKit-compliant mode is on our wishlist, but currently it’s not a high priority and therefore isn't scheduled yet.  In the meantime, hopefully, they implement inputs:file.connect 😄

**Comment by thearperson** [comment]
That @kwblackstone, we have a workaround in our branch now:
https://github.com/cloud-zeta/AdobeUSD/commit/1c9046c08c91119a75db6cb8c75bde3361f4af47

Super hacky... only tested for our use case, probably breaks more things than fixing...

But happy to clean it up and contribute back if you are interested.

**Comment by kwblackstone** [comment]
Thanks for posting it, We will hold off for now, but may come back to it.  Going to close this ticket.

**Comment by lanxinger** [comment]
@thearperson did you test this with the latest macOS beta yet? they do come with updated USD tools including usdchecker now bundled with the OS.

<img width="1067" alt="USD_updates" src="https://github.com/adobe/USD-Fileformat-plugins/assets/20549552/9ba1d612-c0dd-487a-9ec9-8bc5fd23febf">

**Comment by thearperson** [comment]
Haven't tried that yet. But thanks for the recommendation!
