### ISSUE TITLE
CMake configuration error

### ISSUE THREAD

**Issue by waarmond** [adobe/USD-Fileformat-plugins#5]
`cmake -S . -B build -DCMAKE_INSTALL_PREFIX=bin ` is giving me:
```
Building without ASM
CMake Error at CMakeLists.txt:83 (get_filename_component):
  get_filename_component called with incorrect number of arguments

```

**Comment by kwblackstone** [comment]
Hello, when building the plugins you must have a local version of USD.  When running
` cmake -S . -B build` 

the -Dpxr_ROOT parameter is mandatory and must point to your local version of USD.  You can see all options and instructions here:  https://github.com/adobe/USD-Fileformat-plugins?tab=readme-ov-file#3-configure-build-and-install-it  

also if you plan on building the FBX plugin, -DFBXSDK_ROOT is mandatory as well.
